### ISSUE TITLE
Неверный расчёт остатка средств на балансе при оплате с кредитного счёта (CreditAccount) при достижения нулевого баланса

### ISSUE THREAD

**Issue by Mark-Riazantsev** [Mark-Riazantsev/teamProjectJava#10]
# Описание
Происходит неправильный расчёт в методе "pay", класса "CreditAccount", во время оплаты при достижения нулевого баланса.
# Локализация дефекта
https://github.com/Mark-Riazantsev/teamProjectJava/blob/0bd44999bc75f5a69d9600abae291a8492e007f1/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L41-L53
# Шаги воспроизведения 
1. В тесте  [shouldPayWithZeroFinalBalance](https://github.com/Mark-Riazantsev/teamProjectJava/blob/0bd44999bc75f5a69d9600abae291a8492e007f1/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L118-L130) вызвать метод pay() на объекте creditAccount и передать ему значение равное начальному балансу в качестве аргумента.
2. Запустить программу.
3. Посмотреть на выводы в консоли

* Ожидаемый результат : 0 (Исходный баланс уменьшается на сумму покупки 5000)
* Фактический результат : -5000 (Итоговый баланс уменьшается на сумму покупки, не от фактической суммы на балансе 5000, а от 0)

# Скриншот
![image](https://github.com/Mark-Riazantsev/teamProjectJava/assets/138354505/a47c8b10-f9d2-45b2-bc6c-7e6fc7199cf4)

# Окружение
* **Операционная система:** Win 10 19044.2846
* **IntelliJ IDEA** 2023.2 (Trial Edition)
* **Java:** OpenJDK 11

**Comment by Venajan** [comment]
Fixed in bug #9
