### ISSUE TITLE
Неверный расчёт остатка средств на балансе при оплате с кредитного счёта (CreditAccount) при достижения отрицательного баланса

### ISSUE THREAD

**Issue by Mark-Riazantsev** [Mark-Riazantsev/teamProjectJava#11]
# Описание
Происходит неправильный расчёт в методе "pay", класса "CreditAccount", во время оплаты при достижения отрицательного баланса.
# Локализация дефекта
https://github.com/Mark-Riazantsev/teamProjectJava/blob/0bd44999bc75f5a69d9600abae291a8492e007f1/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L41-L53
# Шаги воспроизведения 
1. В тесте  [shouldPayWithNegativeBalance](https://github.com/Mark-Riazantsev/teamProjectJava/blob/0bd44999bc75f5a69d9600abae291a8492e007f1/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L132-L144) вызвать метод pay() на объекте creditAccount и передать ему значение большее чем начальный баланс в качестве аргумента.
2. Запустить программу.
3. Посмотреть на выводы в консоли

* Ожидаемый результат : -1000 (Исходный баланс 5000 уменьшается на сумму покупки 6000)
* Фактический результат : -6000 (Итоговый баланс уменьшается на сумму покупки 6000, не от фактической суммы на балансе 5000, а от 0)

# Скриншот
![image](https://github.com/Mark-Riazantsev/teamProjectJava/assets/138354505/ab17e4e0-4b36-4766-9bab-6c73facd3cf1)

# Окружение
* **Операционная система:** Win 10 19044.2846
* **IntelliJ IDEA** 2023.2 (Trial Edition)
* **Java:** OpenJDK 11

**Comment by Venajan** [comment]
Fixed in bug #9
