### ISSUE TITLE
Неверный расчёт остатка средств на балансе при оплате с кредитного счёта (CreditAccount) при превышении кредитного лимита

### ISSUE THREAD

**Issue by Mark-Riazantsev** [Mark-Riazantsev/teamProjectJava#12]
# Описание
Происходит неправильный расчёт в методе "pay", класса "CreditAccount", во время оплаты при превышении кредитного лимита.
# Локализация дефекта
https://github.com/Mark-Riazantsev/teamProjectJava/blob/0bd44999bc75f5a69d9600abae291a8492e007f1/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L41-L53
# Шаги воспроизведения 
1. В тесте  [shouldPayWithExcessCreditLimit](https://github.com/Mark-Riazantsev/teamProjectJava/blob/0bd44999bc75f5a69d9600abae291a8492e007f1/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L146-L158) вызываем метод pay() на объекте creditAccount и передать ему значение превышающее сумму начального баланса и кредитного лимита в качестве аргумента.
2. Запустить программу.
3. Посмотреть на выводы в консоли

* Ожидаемый результат : 5000 (Исходный баланс 5000 не изменяется)
* Фактический результат : -7000 (Итоговый баланс уменьшается на сумму покупки 12000, превышая кредитный лимит 5000)

# Скриншот
![image](https://github.com/Mark-Riazantsev/teamProjectJava/assets/138354505/78e2c906-472d-4401-be7e-02fd4bd696b0)

# Окружение
* **Операционная система:** Win 10 19044.2846
* **IntelliJ IDEA** 2023.2 (Trial Edition)
* **Java:** OpenJDK 11

**Comment by Venajan** [comment]
Fixed in bug #9
