### ISSUE TITLE
Неверный расчёт процентов по кредиту на баланс счёта кредитного счёта (CreditAccount) в случае нулевого баланса 

### ISSUE THREAD

**Issue by Mark-Riazantsev** [Mark-Riazantsev/teamProjectJava#15]
# Описание
Происходит неправильный расчёт процентов по кредиту в методе "yearChange", класса "CreditAccount", в случае отрицательного баланса
# Локализация дефекта
https://github.com/Mark-Riazantsev/teamProjectJava/blob/d1b15c1c9c68b8d2a59be2df88ff068322c7ac53/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L85-L93
# Начальные условия
Нулевой начальный баланс
# Шаги воспроизведения 
1. В тесте  [shouldCalculatedInterestWithZeroBalance](https://github.com/Mark-Riazantsev/teamProjectJava/blob/d1b15c1c9c68b8d2a59be2df88ff068322c7ac53/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L250-L262) вызвать метод yearChange() на объекте creditAccount и передать ему значение целое положительное значение в качестве аргумента.
2. Запустить программу.
3. Посмотреть на выводы в консоли

* Ожидаемый результат : 0 (При начальном балансе 0, не должен рассчитываться процент по кредиту)
* Фактический результат : 150 (Процент не верно считается от положительной суммы начального баланса 1000)

# Скриншот
![image](https://github.com/Mark-Riazantsev/teamProjectJava/assets/138354505/3bf512cc-0d3d-46af-8c80-dafb78dabbb4)
# Окружение
* **Операционная система:** Win 10 19044.2846
* **IntelliJ IDEA** 2023.2 (Trial Edition)
* **Java:** OpenJDK 11

**Comment by Venajan** [comment]
Тест проходит без изменений в коде
