### ISSUE TITLE
Неверный расчёт остатка средств на балансе при оплате с кредитного счёта (CreditAccount) при начальном нулевом балансе

### ISSUE THREAD

**Issue by Mark-Riazantsev** [Mark-Riazantsev/teamProjectJava#16]
# Описание
Происходит неправильный расчёт в методе "pay", класса "CreditAccount", во время оплаты при начальном нулевом балансе.
# Локализация дефекта
https://github.com/Mark-Riazantsev/teamProjectJava/blob/0bd44999bc75f5a69d9600abae291a8492e007f1/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L41-L53
# Начальные условия
Нулевой начальный баланс
# Шаги воспроизведения 
1. В тесте  [shouldPayWithZeroInitialBalance](https://github.com/Mark-Riazantsev/teamProjectJava/blob/d1b15c1c9c68b8d2a59be2df88ff068322c7ac53/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L117-L129) вызвать метод pay() на объекте creditAccount и передать ему целое положительное значение в качестве аргумента.
2. Запустить программу.
3. Посмотреть на выводы в консоли

* Ожидаемый результат : true (Исходный баланс 0 уменьшается на сумму покупки 5000 и должен быть равен -5000)
* Фактический результат : false (Баланс после покупки 5000, не меньше кредитного лимита 5000, но выдаёт false)

# Скриншот
![image](https://github.com/Mark-Riazantsev/teamProjectJava/assets/138354505/f7e6526c-8403-4ab4-ac1b-e0442027db15)

# Окружение
* **Операционная система:** Win 10 19044.2846
* **IntelliJ IDEA** 2023.2 (Trial Edition)
* **Java:** OpenJDK 11

**Comment by Venajan** [comment]
Fixed in bug #9
