### ISSUE TITLE
Не выдает исключение вида IllegalArgumentException на сберегательном счету, в случае если начальный баланс отрицательный

### ISSUE THREAD

**Issue by Venajan** [Mark-Riazantsev/teamProjectJava#17]
# Описание
Во время тестирования, в случае если начальный баланс отрицательный, не выдает исключения вида IllegalArgumentException

# Локация дефекта
https://github.com/Mark-Riazantsev/teamProjectJava/blob/b6327e2993752d358ca2ded7ea221c5aa9e67cdc/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22-L32

# Шаги воспроизведения
1. Открыть проект в IDEA
2. Создать класс SavingAccount:
   https://github.com/Mark-Riazantsev/teamProjectJava/blob/b6327e2993752d358ca2ded7ea221c5aa9e67cdc/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L1-L99
3. Создать тест в классе SavingAccountTest
   https://github.com/Mark-Riazantsev/teamProjectJava/blob/33462b61f88c808ced04cb7b9a4a6e5ca559dfbb/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L244-L254
4. Запустить тест **shouldNegativeInitialBalance** на 244 строке и посмотреть результат:
Ожидаемый результат : Выдает ошибку исключения "Начальный баланс не может быть отрицательным, а у вас: " + initialBalance
Фактический результат : Исключения не выдается.

# Скриншот 
![image](https://github.com/Mark-Riazantsev/teamProjectJava/assets/132198969/d114f5db-fc06-4dc8-bed4-db69e9d42f01)

# Окружение
* Операционная система: Windows 10 Pro
* IDE: IntelliJ IDEA 2023.11 (Community Edition)
* Java: OpenJDK 11

**Comment by Mark-Riazantsev** [comment]
Fixed in bug #3
