### ISSUE TITLE
Не выдает исключение вида IllegalArgumentException на сберегательном счету, в случае если максимальный баланс отрицательный

### ISSUE THREAD

**Issue by Venajan** [Mark-Riazantsev/teamProjectJava#19]
# Описание
Во время тестирования, в случае если максимальный баланс отрицательный, не выдает исключения вида IllegalArgumentException

# Локация дефекта
https://github.com/Mark-Riazantsev/teamProjectJava/blob/b6327e2993752d358ca2ded7ea221c5aa9e67cdc/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22-L32

# Шаги воспроизведения
1. Открыть проект в IDEA
2. Создать класс SavingAccount:
   https://github.com/Mark-Riazantsev/teamProjectJava/blob/b6327e2993752d358ca2ded7ea221c5aa9e67cdc/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L1-L99
3. Создать тест в классе SavingAccountTest
   https://github.com/Mark-Riazantsev/teamProjectJava/blob/33462b61f88c808ced04cb7b9a4a6e5ca559dfbb/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L270-L280
4. Запустить тест **shouldNegativeMaxBalance** на 270 строке и посмотреть результат:
Ожидаемый результат : Выдает ошибку исключения "Максимальный баланс не может быть отрицательным, а у вас: " + maxBalance
Фактический результат : Исключения не выдается.

# Скриншот 
![image](https://github.com/Mark-Riazantsev/teamProjectJava/assets/132198969/36ae0c04-2d5b-469d-8e57-e3eeefaa35a2)

# Окружение
* Операционная система: Windows 10 Pro
* IDE: IntelliJ IDEA 2023.11 (Community Edition)
* Java: OpenJDK 11

**Comment by Mark-Riazantsev** [comment]
Fixed in bug#2
